---
title: "Sudoku Solver Analysis"
author: "Steven Kim"
date: "today"
format: pdf
execute:
  warning: false
  message: false
---
```{r}
#| include: false
options(repos = c(CRAN = "https://cran.rstudio.com/"))
```

Check for packages:
```{r}
#| echo: false
library(tidyverse)
library(dplyr)
library(here)
```

Read Data:
```{r}
sudoku_data <- read_csv(here("data", "sample_10000.csv"))

sudoku_data_processed <- sudoku_data |>
  filter(is_solved == TRUE) |>
  filter(difficulty != 0)

glimpse(sudoku_data_processed)
```

Preliminary Graphs:
```{r}
ggplot(sudoku_data_processed, aes(x = factor(clues), y = difficulty)) +
  geom_jitter(alpha = 0.1, width = 0.3) +
  geom_boxplot(alpha = 0.5, color = "darkgreen") +
  labs(title = "Difficulty by Number of Clues") +
  theme_minimal()
```

```{r}
ggplot(sudoku_data_processed, aes(x = solve_time_ms, y = difficulty)) +
  geom_point(alpha = 0.5) +
# coord_cartesian(xlim = c(0, 2500000)) +
  labs(title = "Difficulty by Solve Time") +
  theme_minimal()
```

```{r}
ggplot(sudoku_data_processed, aes(x = nodes_explored, y = difficulty)) +
  geom_point(alpha = 0.5) +
  coord_cartesian(xlim = c(0, 2500000)) +
  labs(title = "Difficulty by Nodes Explored") +
  theme_minimal()
```

```{r}
ggplot(sudoku_data_processed, aes(x = factor(clues), y = nodes_explored)) +
  geom_jitter(alpha = 0.1, width = 0.3) +
  geom_boxplot(alpha = 0.5, color = "darkgreen") +
  coord_cartesian(ylim = c(0, 500000)) +
  labs(title = "Nodes Explored by Number of Clues") +
  theme_minimal()
```